export const productList = [
  {
    nombre: "Bebida 2lt",
    marca: "Coca Cola",
    img: "https://picsum.photos/200?random=1",
    precio: "1.990",
    categoria: "Bebidas",
  },
  {
    nombre: "Bebida 2lt",
    marca: "Sprite",
    img: "https://picsum.photos/200?random=2",
    precio: "1.790",
    categoria: "Bebidas",
  },
  {
    nombre: "Bebida 1lt",
    marca: "Coca Cola",
    img: "https://picsum.photos/200?random=3",
    precio: "1.290",
    categoria: "Bebidas",
  },
  {
    nombre: "Six Pack 500cc",
    marca: "Escudo",
    img: "https://picsum.photos/200?random=4",
    precio: "2.990",
    categoria: "Cervezas",
  },
  {
    nombre: "Six Pack 500cc",
    marca: "Andes",
    img: "https://picsum.photos/200?random=5",
    precio: "2.890",
    categoria: "Cervezas",
  },
  {
    nombre: "Pisco 1lt",
    marca: "Alto del Carmen",
    img: "https://picsum.photos/200?random=6",
    precio: "5.290",
    categoria: "Destilados",
  },
  {
    nombre: "Pisco 750cc",
    marca: "Alto del Carmen",
    img: "https://picsum.photos/200?random=8",
    precio: "3.790",
    categoria: "Destilados",
  },
  {
    nombre: "Agua mineral 1lt",
    marca: "Cachantun",
    img: "https://picsum.photos/200?random=9",
    precio: "1.490",
    categoria: "Agua",
  },
  {
    nombre: "Agua mineral 700cc",
    marca: "Cachantun",
    img: "https://picsum.photos/200?random=10",
    precio: "990",
    categoria: "Agua",
  },
  {
    nombre: "Papas Fritas 200g",
    marca: "Lays",
    img: "https://picsum.photos/200?random=11",
    precio: "1.680",
    categoria: "Comida",
  },
  {
    nombre: "Vino Tinto 2lt",
    marca: "Gato",
    img: "https://picsum.photos/200?random=12",
    precio: "1.290",
    categoria: "Vinos",
  },
  {
    nombre: "Bebida 2lt",
    marca: "Coca Cola",
    img: "https://picsum.photos/200?random=13",
    precio: "1.990",
    categoria: "Bebidas",
  },
  {
    nombre: "Bebida 2lt",
    marca: "Sprite",
    img: "https://picsum.photos/200?random=22",
    precio: "1.790",
    categoria: "Bebidas",
  },
  {
    nombre: "Bebida 1lt",
    marca: "Coca Cola",
    img: "https://picsum.photos/200?random=32",
    precio: "1.290",
    categoria: "Bebidas",
  },
  {
    nombre: "Six Pack 500cc",
    marca: "Escudo",
    img: "https://picsum.photos/200?random=42",
    precio: "2.990",
    categoria: "Cervezas",
  },
  {
    nombre: "Six Pack 500cc",
    marca: "Andes",
    img: "https://picsum.photos/200?random=52",
    precio: "2.890",
    categoria: "Cervezas",
  },
  {
    nombre: "Pisco 1lt",
    marca: "Alto del Carmen",
    img: "https://picsum.photos/200?random=62",
    precio: "5.290",
    categoria: "Destilados",
  },
  {
    nombre: "Pisco 750cc",
    marca: "Alto del Carmen",
    img: "https://picsum.photos/200?random=82",
    precio: "3.790",
    categoria: "Destilados",
  },
  {
    nombre: "Agua mineral 1lt",
    marca: "Cachantun",
    img: "https://picsum.photos/200?random=92",
    precio: "1.490",
    categoria: "Agua",
  },
  {
    nombre: "Agua mineral 700cc",
    marca: "Cachantun",
    img: "https://picsum.photos/200?random=102",
    precio: "990",
    categoria: "Agua",
  },
  {
    nombre: "Papas Fritas 200g",
    marca: "Lays",
    img: "https://picsum.photos/200?random=112",
    precio: "1.680",
    categoria: "Comida",
  },
  {
    nombre: "Vino Tinto 2lt",
    marca: "Gato",
    img: "https://picsum.photos/200?random=73",
    precio: "1.290",
    categoria: "Vinos",
  },
  {
    nombre: "Bebida 2lt",
    marca: "Coca Cola",
    img: "https://picsum.photos/200?random=13",
    precio: "1.990",
    categoria: "Bebidas",
  },
  {
    nombre: "Bebida 2lt",
    marca: "Sprite",
    img: "https://picsum.photos/200?random=23",
    precio: "1.790",
    categoria: "Bebidas",
  },
  {
    nombre: "Bebida 1lt",
    marca: "Coca Cola",
    img: "https://picsum.photos/200?random=33",
    precio: "1.290",
    categoria: "Bebidas",
  },
  {
    nombre: "Six Pack 500cc",
    marca: "Escudo",
    img: "https://picsum.photos/200?random=43",
    precio: "2.990",
    categoria: "Cervezas",
  },
  {
    nombre: "Six Pack 500cc",
    marca: "Andes",
    img: "https://picsum.photos/200?random=53",
    precio: "2.890",
    categoria: "Cervezas",
  },
  {
    nombre: "Pisco 1lt",
    marca: "Alto del Carmen",
    img: "https://picsum.photos/200?random=63",
    precio: "5.290",
    categoria: "Destilados",
  },
  {
    nombre: "Pisco 750cc",
    marca: "Alto del Carmen",
    img: "https://picsum.photos/200?random=83",
    precio: "3.790",
    categoria: "Destilados",
  },
  {
    nombre: "Agua mineral 1lt",
    marca: "Cachantun",
    img: "https://picsum.photos/200?random=93",
    precio: "1.490",
    categoria: "Agua",
  },
  {
    nombre: "Agua mineral 700cc",
    marca: "Cachantun",
    img: "https://picsum.photos/200?random=103",
    precio: "990",
    categoria: "Agua",
  },
  {
    nombre: "Papas Fritas 200g",
    marca: "Lays",
    img: "https://picsum.photos/200?random=113",
    precio: "1.680",
    categoria: "Comida",
  },
  {
    nombre: "Vino Tinto 2lt",
    marca: "Gato",
    img: "https://picsum.photos/200?random=73",
    precio: "1.290",
    categoria: "Vinos",
  },
  {
    nombre: "Bebida 2lt",
    marca: "Coca Cola",
    img: "https://picsum.photos/200?random=15",
    precio: "1.990",
    categoria: "Bebidas",
  },
  {
    nombre: "Bebida 2lt",
    marca: "Sprite",
    img: "https://picsum.photos/200?random=25",
    precio: "1.790",
    categoria: "Bebidas",
  },
  {
    nombre: "Bebida 1lt",
    marca: "Coca Cola",
    img: "https://picsum.photos/200?random=35",
    precio: "1.290",
    categoria: "Bebidas",
  },
  {
    nombre: "Six Pack 500cc",
    marca: "Escudo",
    img: "https://picsum.photos/200?random=45",
    precio: "2.990",
    categoria: "Cervezas",
  },
  {
    nombre: "Six Pack 500cc",
    marca: "Andes",
    img: "https://picsum.photos/200?random=55",
    precio: "2.890",
    categoria: "Cervezas",
  },
  {
    nombre: "Pisco 1lt",
    marca: "Alto del Carmen",
    img: "https://picsum.photos/200?random=65",
    precio: "5.290",
    categoria: "Destilados",
  },
  {
    nombre: "Pisco 750cc",
    marca: "Alto del Carmen",
    img: "https://picsum.photos/200?random=85",
    precio: "3.790",
    categoria: "Destilados",
  },
  {
    nombre: "Agua mineral 1lt",
    marca: "Cachantun",
    img: "https://picsum.photos/200?random=95",
    precio: "1.490",
    categoria: "Agua",
  },
  {
    nombre: "Agua mineral 700cc",
    marca: "Cachantun",
    img: "https://picsum.photos/200?random=105",
    precio: "990",
    categoria: "Agua",
  },
  {
    nombre: "Papas Fritas 200g",
    marca: "Lays",
    img: "https://picsum.photos/200?random=115",
    precio: "1.680",
    categoria: "Comida",
  },
  {
    nombre: "Vino Tinto 2lt",
    marca: "Gato",
    img: "https://picsum.photos/200?random=75",
    precio: "1.290",
    categoria: "Vinos",
  },
  {
    nombre: "Bebida 2lt",
    marca: "Coca Cola",
    img: "https://picsum.photos/200?random=16",
    precio: "1.990",
    categoria: "Bebidas",
  },
  {
    nombre: "Bebida 2lt",
    marca: "Sprite",
    img: "https://picsum.photos/200?random=26",
    precio: "1.790",
    categoria: "Bebidas",
  },
  {
    nombre: "Bebida 1lt",
    marca: "Coca Cola",
    img: "https://picsum.photos/200?random=36",
    precio: "1.290",
    categoria: "Bebidas",
  },
  {
    nombre: "Six Pack 500cc",
    marca: "Escudo",
    img: "https://picsum.photos/200?random=46",
    precio: "2.990",
    categoria: "Cervezas",
  },
  {
    nombre: "Six Pack 500cc",
    marca: "Andes",
    img: "https://picsum.photos/200?random=56",
    precio: "2.890",
    categoria: "Cervezas",
  },
  {
    nombre: "Pisco 1lt",
    marca: "Alto del Carmen",
    img: "https://picsum.photos/200?random=66",
    precio: "5.290",
    categoria: "Destilados",
  },
  {
    nombre: "Pisco 750cc",
    marca: "Alto del Carmen",
    img: "https://picsum.photos/200?random=86",
    precio: "3.790",
    categoria: "Destilados",
  },
  {
    nombre: "Agua mineral 1lt",
    marca: "Cachantun",
    img: "https://picsum.photos/200?random=96",
    precio: "1.490",
    categoria: "Agua",
  },
  {
    nombre: "Agua mineral 700cc",
    marca: "Cachantun",
    img: "https://picsum.photos/200?random=106",
    precio: "990",
    categoria: "Agua",
  },
  {
    nombre: "Papas Fritas 200g",
    marca: "Lays",
    img: "https://picsum.photos/200?random=116",
    precio: "1.680",
    categoria: "Comida",
  },
  {
    nombre: "Vino Tinto 2lt",
    marca: "Gato",
    img: "https://picsum.photos/200?random=76",
    precio: "1.290",
    categoria: "Vinos",
  },
];
